const {
  VITE_PUBLIC_THEMOVIEDB3_BASE_URL,
  VITE_PUBLIC_THEMOVIEDB3_API_KEY,
  VITE_PUBLIC_THEMOVIE_IMAGE_THUMBNAIL,
  VITE_PUBLIC_THEMOVIE_IMAGE_ORIGINAL,
} = import.meta.env;

export {
  VITE_PUBLIC_THEMOVIEDB3_BASE_URL,
  VITE_PUBLIC_THEMOVIEDB3_API_KEY,
  VITE_PUBLIC_THEMOVIE_IMAGE_THUMBNAIL,
  VITE_PUBLIC_THEMOVIE_IMAGE_ORIGINAL,
};
